apiVersion: v1
kind: ConfigMap
metadata:
  name: web-project-config
data:
  api-endpoints.properties: |
    api.campaigns.url=http://20.23.136.104:5000/campaigns
    api.tasks.url=http://20.23.136.104:5000/tasks
    api.workers.url=http://20.23.136.104:5000/workers
